apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: demo-votingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: demo-votingapp
  template:
    metadata:
      name: redis-pod
      labels:
        app: demo-votingapp
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379