apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp-pod
  labels:
    app: demo-votingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: votingapp-pod
      app: demo-votingapp
  template:
    metadata:
      name: votingapp-pod
      app: demo-votingapp
      labels:
        name: votingapp-pod
        app: demo-votingapp
    spec:
      containers:
        - name: demo-votingapp
          image: dockersamples/examplevotingapp_vote
          ports:
          - containerPort: 80