apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp-worker
  labels:
    name: votingapp-worker
    app: demo-votingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: votingapp-worker
      app: demo-votingapp
  template:
    metadata:
      name: votingapp-worker
      labels:
        name: votingapp-worker
        app: demo-votingapp
    spec:
      containers:
        - name: votingapp-worker
          image: tadamo/examplevotingapp_worker
